
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name : FlaskWebServer
    init: cd flask && pip install -r requirements.txt && npm i -g nodemon && nodemon app.py # runs during prebuild
  - name : AngWebServer
    init: cd MondialiAng && npm i -g @angular/cli && npm i && NG_APP_URL=$GITPOD_WORKSPACE_URL ng serve --disable-host-check && npm install leaflet@1.7.1 # runs during prebuild

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-browser
    visibility : public 
  - port: 5000
    visibility : public 
